<?xml version="1.0" encoding="UTF-8"?>   
<!DOCTYPE students [ <!ELEMENT students (student+)>   
<!ELEMENT student (name, email, age)>   
  <!ELEMENT name (#PCDATA)>   
    <!ATTLIST name id CDATA #REQUIRED>   
      <!ELEMENT email (#PCDATA)>   
        <!ELEMENT age (#PCDATA)>   
          ]>   
          <students>   
            <student>   
              <name id="1">Purnima Bohara</name>   
              <email>purnima4@gmail.com</email>   
              <age>21</age>   
            </student>   
            <student>   
              <name id="2">Kimberly Clark</name>   
              <email>kimberlyclark@gmail.com</email>   
              <age>22</age>   
            </student>   
            <student>   
              <name id="3">Isha Shah</name>   
              <email>shah169@gmail.com</email>   
<age>21</age>   
</student>   
</students> 